---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks


- Dev DBM :
    - Gitlab:
        - abbr: GL
          href: https://gitlab.dbm-agence.com/
          icon: gitlab
    - Discourse:
        - abbr: DS
          href: https://discourse.dbm-agence.com/
    - Axeptio: 
        - abbr : Ax
          href : https://admin.axeptio.eu/projects?perPage=50
    - GTM:
        - abbr : GTM
          href : https://tagmanager.google.com/
          icon : google
- DBM :
    - Procedure:
        - abbr : PR
          href : https://debussac.sharepoint.com/sites/procedures-dbm
    - Monday: 
        - abbr : MD
          href : https://dbm-agence-team.monday.com/


          
