---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Nos Wordpress:
    -  Debussac:
          href: https://www.debussac.net/
          icon: wordpress
    -  ATUAH:
          href: https://association-traitdunion-handis.fr/
          icon: wordpress
    -  GPFranceMoto:
          href: https://www.gpfrancemoto.fr/
          icon: wordpress
    -  Oxsitis:
          href: https://www.oxsitis.fr/
          icon: wordpress
    -  CCI:

- Nos elementor: 
    - Murmure: 
        href: https://www.bistrotmurmure.fr/
    - F.Initiative:
        href: https://www.f-initiatives.com/


# - GitLab :
#     -  DBM:
#         type: gitlab
#         url: https://gitlab.dbm-agence.com/
#         token: TON_TOKEN_GITLAB
#         projects:
#             - ton-namespace/ton-projet
#             - ton-namespace/ton-autre-projet
#         showPipelines: true
#         showIssues: true
#         showMergeRequests: true




   



