---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- status:
    title: Statut Site Web
    items:
        - name: Site principal
            url: https://association-traitdunion-handis.fr/
            method: GET
            timeout: 5000  
